"""Add confirmed column to User

Revision ID: 707b8f6c2c81
Revises: 9abdce1299ca
Create Date: 2026-05-24 11:22:01.385278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '707b8f6c2c81'
down_revision = '9abdce1299ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('confirmed')

    # ### end Alembic commands ###
